version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookers2

  web:
    build:
      context: ./
      target: development
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/bookers2
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  database:
