# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    
    # Runs a single command using the runners shell
    - name: Heroku CLI Install
      run: |
        curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
      
    - name: Heroku Login
      run: |
       cat <<<EOF > ~/.netrc
        machine api.heroku.com
            login ${ HEROKU_EMAIL }
            password ${ HEROKU_TOKEN }
        machine git.heroku.com
            login { HEROKU_EMAIL }
            password ${ HEROKU_TOKEN }
       EOF
       heroku login
      env:
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
